FROM wordpress:cli

# you can build this image by running:
# docker build . -f Dockerfile_wordpress --tag img_cb_wordpress
# this will end up creating an image called 'img_cb_wordpress'
# you can create a container from this image by running:
# docker container create --name cntr_cb_wordpress img_cb_wordpress
# docker container start cntr_cb_wordpress

LABEL maintainer "Sher Chowdhury"

USER root
RUN mkdir -p /etc/X11/fs
RUN chown xfs:xfs /etc/X11/fs
#RUN echo "alias ll='ls -l'" >> /etc/bash
RUN id 
RUN pwd
RUN mkdir /image_build_scripts
COPY image_build_scripts /image_build_scripts
RUN chown -R www-data:www-data /image_build_scripts
# https://make.wordpress.org/cli/handbook/common-issues/#php-fatal-error-allowed-memory-size-of-999999-bytes-exhausted-tried-to-allocate-99-bytes
COPY image_build_scripts/uploads_wp_cli.ini /usr/local/etc/php/conf.d/uploads.ini
USER xfs
# https://make.wordpress.org/cli/handbook/config/
RUN mkdir ~/.wp-cli
COPY image_build_scripts/wp-cli-config.yml /etc/X11/fs/.wp-cli/config.yml 
# RUN wp package install pojome/elementor

CMD ["/image_build_scripts/bootstrap.sh"]