version: '3.3'

services:
  db:
    container_name: cntr_wp_db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      # https://docs.docker.com/compose/environment-variables/#the-env-file
      MYSQL_DATABASE: ${db_name}
      MYSQL_USER: ${db_user}
      MYSQL_PASSWORD: ${db_password}

  wordpress:
    container_name: cntr_wp
    domainname: net
    hostname: codingbee
    depends_on:
      - db
    image: img_wp:latest
    ports:
      - "8000:80"
    restart: always
    environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${db_user}
       WORDPRESS_DB_PASSWORD: ${db_password}
       WORDPRESS_DB_NAME: ${db_name}
    volumes:
      - wp_data:/var/www/html
#      - image_build_scripts/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    extra_hosts:
       - "codingbee.net:127.0.0.1"
  wordpress-cli:
    container_name: cntr_wp_cli
    depends_on:
      - db
      - wordpress 
    image: img_wp_cli
    environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${db_user}
       WORDPRESS_DB_PASSWORD: ${db_password}
       WORDPRESS_DB_NAME: ${db_name}
    user: xfs
    env_file:
      - cntr_wp_cli.env
    volumes:
      - wp_data:/var/www/html
    extra_hosts:
       - "codingbee.net:127.0.0.1"
volumes:
  db_data: {}
  wp_data: {}