FROM wordpress:cli

# you can build this image by running:
# docker build . -f Dockerfile_wordpress --tag img_cb_wordpress
# this will end up creating an image called 'img_cb_wordpress'
# you can create a container from this image by running:
# docker container create --name cntr_cb_wordpress img_cb_wordpress
# docker container start cntr_cb_wordpress

LABEL maintainer "Sher Chowdhury"

USER root
RUN mkdir -p /etc/X11/fs
RUN chown xfs:xfs /etc/X11/fs
#RUN echo "alias ll='ls -l'" >> /etc/bash
RUN id 
RUN pwd
RUN mkdir /image_build_scripts
COPY image_build_scripts /image_build_scripts
RUN chown -R www-data:www-data /image_build_scripts
USER www-data 
CMD ["/image_build_scripts/bootstrap.sh"]
